# Generated by Django 6.0.2 on 2026-04-28 22:48

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='proveedor',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('razon_social'), name='uq_proveedores_razon_social_ci'),
        ),
    ]
