site_name: SofInventory ERP
site_description: Manuales y documentación de calidad del sistema SofInventory.
site_author: Alejandro Sepúlveda Duarte y Lucy Estefany Izquierdo Jaramillo


theme:
  name: material
  language: es
  palette:
    scheme: default
    primary: indigo
    accent: indigo
  features:
    - navigation.tabs          # Pestañas superiores
    - navigation.top           # Botón para volver arriba
    - search.suggest           # Sugerencias en búsqueda
    - search.highlight         # Resaltar resultados de búsqueda
    - content.code.copy        # Botón de copiar en bloques de código
    - toc.integrate            # Integra la tabla de contenidos para limpiar espacio

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
extra_javascript:
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js

extra_css:
  - docs/extra.css

nav:
  - Manual de Usuario: MANUAL_USUARIO.md
  - Manual Técnico: MANUAL_TECNICO.md
  - Diseño y calidad del software: Aplicacion_buenas_practicas_calidad_SofInventory.md
  - Instrumentos de calidad del software: Diligenciamiento_instrumentos_calidad_SofInventory.md
  - Bitácora: Bitacora_procesos_documentados_SofInventory.md

