# Generated by Django 6.0.2 on 2026-03-08 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('productos', '0006_producto_descripcion'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_venta', models.CharField(editable=False, max_length=20, unique=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tipo_iva', models.CharField(choices=[('automatico', 'Automático 19%'), ('manual', 'Manual')], default='automatico', max_length=10)),
                ('iva_porcentaje', models.DecimalField(decimal_places=2, default=19, max_digits=5)),
                ('iva_monto', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('debito', 'Tarjeta Débito'), ('credito', 'Tarjeta Crédito'), ('transferencia', 'Transferencia'), ('nequi', 'Nequi'), ('daviplata', 'DaviPlata'), ('otro', 'Otro')], max_length=15)),
                ('efectivo_recibido', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('cambio', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('numero_tarjeta', models.CharField(blank=True, max_length=4, null=True)),
                ('aprobacion_tarjeta', models.CharField(blank=True, max_length=50, null=True)),
                ('comprobante_transferencia', models.CharField(blank=True, max_length=100, null=True)),
                ('otro_metodo', models.CharField(blank=True, max_length=100, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('completada', 'Completada'), ('anulada', 'Anulada')], default='completada', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_anulacion', models.DateTimeField(blank=True, null=True)),
                ('motivo_anulacion', models.TextField(blank=True, null=True)),
                ('anulado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas_anuladas', to='usuarios.usuario')),
                ('cliente', models.ForeignKey(blank=True, help_text='Null = Cliente General', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='clientes.cliente')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas_realizadas', to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'ventas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cantidad', models.IntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=14)),
                ('nombre_producto', models.CharField(max_length=150)),
                ('sku_producto', models.CharField(max_length=200)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_venta', to='productos.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalles de Venta',
                'db_table': 'detalle_ventas',
            },
        ),
    ]
