# Generated by Django 6.0.2 on 2026-03-07 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0006_producto_descripcion'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('responsable', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('capacidad', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('mantenimiento', 'En Mantenimiento')], default='activo', max_length=15)),
                ('notas', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='almacenes_creados', to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Almacén',
                'verbose_name_plural': 'Almacenes',
                'db_table': 'almacenes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionRangosStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_bajo', models.IntegerField(default=5)),
                ('stock_medio', models.IntegerField(default=20)),
                ('stock_alto', models.IntegerField(default=21)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rangos_actualizados', to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Configuración de Rangos de Stock',
                'db_table': 'configuracion_rangos_stock',
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA_COMPRA', 'Entrada por Compra'), ('SALIDA_VENTA', 'Salida por Venta'), ('TRASLADO_ENTRADA', 'Traslado - Entrada'), ('TRASLADO_SALIDA', 'Traslado - Salida'), ('AJUSTE_POSITIVO', 'Ajuste Positivo'), ('AJUSTE_NEGATIVO', 'Ajuste Negativo'), ('DEVOLUCION_COMPRA', 'Devolución a Proveedor'), ('DEVOLUCION_VENTA', 'Devolución de Cliente')], max_length=25)),
                ('cantidad', models.IntegerField()),
                ('costo_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('referencia_tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('referencia_id', models.PositiveIntegerField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('almacen_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_entrada', to='inventario.almacen')),
                ('almacen_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_salida', to='inventario.almacen')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_creados', to='usuarios.usuario')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='productos.producto')),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'db_table': 'movimientos_inventario',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Traslado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_TRANSITO', 'En Tránsito'), ('COMPLETADO', 'Completado'), ('ANULADO', 'Anulado')], default='PENDIENTE', max_length=15)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('almacen_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traslados_entrada', to='inventario.almacen')),
                ('almacen_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traslados_salida', to='inventario.almacen')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traslados_creados', to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Traslado',
                'verbose_name_plural': 'Traslados',
                'db_table': 'traslados',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='TrasladoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.producto')),
                ('traslado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.traslado')),
            ],
            options={
                'db_table': 'traslados_detalle',
            },
        ),
        migrations.CreateModel(
            name='StockAlmacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='inventario.almacen')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='productos.producto')),
            ],
            options={
                'verbose_name': 'Stock por Almacén',
                'verbose_name_plural': 'Stocks por Almacén',
                'db_table': 'stock_almacen',
                'unique_together': {('producto', 'almacen')},
            },
        ),
    ]
