# Generated by Django 6.0.2 on 2026-03-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_producto_especificaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
