# Generated by Django 6.0.2 on 2026-03-05 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('tipo_control', models.CharField(choices=[('GENERAL', 'General'), ('HERRAMIENTA', 'Herramienta'), ('ELECTRICO', 'Eléctrico'), ('LIQUIDO', 'Líquido'), ('TORNILLERIA', 'Tornillería')], default='GENERAL', max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categorias_creadas', to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'categorias',
                'ordering': ['nombre'],
            },
        ),
    ]
