# Generated by Django 6.0.2 on 2026-03-06 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=200, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('marca', models.CharField(max_length=100)),
                ('referencia', models.CharField(max_length=100)),
                ('unidad_medida', models.CharField(choices=[('Unidad', 'Unidad'), ('Caja', 'Caja'), ('Metro', 'Metro'), ('Litro', 'Litro'), ('Galon', 'Galón'), ('Rollo', 'Rollo'), ('Bulto', 'Bulto'), ('Kilo', 'Kilo')], default='Unidad', max_length=10)),
                ('precio_compra', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio_venta', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('stock', models.IntegerField(default=0)),
                ('stock_minimo', models.IntegerField(default=0)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente por configurar'), ('activo', 'Activo'), ('inactivo', 'Inactivo')], default='pendiente', max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='productos.categoria')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos_creados', to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'productos',
                'ordering': ['nombre'],
            },
        ),
    ]
