# Generated by Django 6.0.2 on 2026-04-30 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SesionAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(editable=False, max_length=80, unique=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('expira_en', models.DateTimeField()),
                ('ultima_actividad', models.DateTimeField(auto_now=True)),
                ('activa', models.BooleanField(default=True)),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_api', to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Sesion API',
                'verbose_name_plural': 'Sesiones API',
                'db_table': 'sesiones_api',
                'ordering': ['-creada_en'],
            },
        ),
    ]
