# Generated by Django 6.0.4 on 2026-06-16 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_sesionapi'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cuenta_bloqueada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_bloqueo',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='IntentoFallidoLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_intento', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos_fallidos', to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Intento Fallido de Login',
                'verbose_name_plural': 'Intentos Fallidos de Login',
                'db_table': 'intentos_fallidos_login',
                'ordering': ['-fecha_intento'],
                'indexes': [models.Index(fields=['usuario', '-fecha_intento'], name='intentos_fa_usuario_5ca77e_idx')],
            },
        ),
    ]
